import turtle
t = turtle.Pen()
turtle.title("Lab4")


def desen1():
    t.speed(1)
    t.shape("turtle")
    t.fd(200)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(100)
    t.penup()
    t.goto(30, 30)
    t.pendown()
    t.fd(25)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(25)
    t.lt(90)
    t.fd(50)
    t.reset()


def desen2():
    t.speed(1)
    t.lt(50)
    t.fd(150)
    t.circle(50, 200)
    t.rt(150)
    t.circle(50, 200)
    t.fd(150)
    t.reset()


def desen3():
    casa_unu = turtle.Pen()
    casa_unu.penup()
    casa_unu.speed(2)
    casa_doi = casa_unu.clone()
    casa_unu.goto(150, 150)
    casa_unu.pendown()
    casa_unu.fd(100)
    casa_unu.lt(90)
    casa_unu.fd(100)
    casa_unu.lt(90)
    casa_unu.fd(100)
    casa_unu.lt(90)
    casa_unu.fd(100)
    casa_unu.lt(90)
    casa_unu.penup()
    casa_unu.goto(190, 150)
    casa_unu.pendown()
    casa_unu.fd(20)
    casa_unu.lt(90)
    casa_unu.fd(40)
    casa_unu.lt(90)
    casa_unu.fd(20)
    casa_unu.lt(90)
    casa_unu.fd(40)
    casa_unu.lt(90)
    casa_unu.penup()
    casa_unu.penup()
    casa_unu.goto(200, 200)
    casa_unu.pendown()
    casa_unu.fd(30)
    casa_unu.lt(90)
    casa_unu.fd(30)
    casa_unu.lt(90)
    casa_unu.fd(30)
    casa_unu.lt(90)
    casa_unu.fd(30)
    casa_unu.lt(90)
    casa_unu.penup()
    casa_unu.goto(150, 250)
    casa_unu.pendown()
    casa_unu.fd(100)
    casa_unu.lt(120)
    casa_unu.fd(100)
    casa_unu.lt(120)
    casa_unu.fd(100)
    casa_doi.penup()
    casa_doi.goto(-100, -100)
    casa_doi.pendown()
    casa_doi.fd(100)
    casa_doi.lt(90)
    casa_doi.fd(100)
    casa_doi.lt(90)
    casa_doi.fd(100)
    casa_doi.lt(90)
    casa_doi.fd(100)
    casa_doi.lt(90)
    casa_doi.penup()
    casa_doi.goto(-60, -100)
    casa_doi.pendown()
    casa_doi.fd(20)
    casa_doi.lt(90)
    casa_doi.fd(40)
    casa_doi.lt(90)
    casa_doi.fd(20)
    casa_doi.lt(90)
    casa_doi.fd(40)
    casa_doi.lt(90)
    casa_doi.penup()
    casa_doi.goto(-60, -50)
    casa_doi.pendown()
    casa_doi.fd(30)
    casa_doi.lt(90)
    casa_doi.fd(30)
    casa_doi.lt(90)
    casa_doi.fd(30)
    casa_doi.lt(90)
    casa_doi.fd(30)
    casa_doi.lt(90)
    casa_doi.penup()
    casa_doi.goto(-100, 0)
    casa_doi.pendown()
    casa_doi.fd(100)
    casa_doi.lt(120)
    casa_doi.fd(100)
    casa_doi.lt(120)
    casa_doi.fd(100)
    casa_unu.reset()
    casa_doi.reset()


def meniu():
    print("1. Doua dreptunghiuri")
    print("2. Inima")
    print("3. Doua case")

    optiune = input("Alege un nr de la 1 la 3: ")
    if optiune == '1':
        desen1()
    elif optiune == '2':
        desen2()
    elif optiune == '3':
        desen3()
    else:
        print("Mai incearca")


if __name__ == "__main__":
    meniu()
